SET datestyle = 'iso,mdy';  
ALTER TABLE sales_dataset_rfm_prj
ALTER COLUMN quantityordered TYPE numeric USING(trim(ordernumber)::numeric),
ALTER COLUMN priceeach TYPE decimal USING(trim(ordernumber)::decimal),
ALTER COLUMN orderlinenumber TYPE numeric USING(trim(ordernumber)::numeric),
ALTER COLUMN sales TYPE numeric USING(trim(ordernumber)::numeric),
ALTER COLUMN msrp TYPE numeric  USING(trim(ordernumber)::numeric),
ALTER COLUMN orderdate TYPE date USING(TRIM(orderdate)::time),
/*2. check null/blank*/ 
ALTER TABLE sales_dataset_rfm_prj
ADD CHECK ( ORDERNUMBER IS NOT NULL),
ADD CHECK ( QUANTITYORDERED IS NOT NULL),
ADD CHECK ( PRICEEACH IS NOT NULL),                      
ADD CHECK ( ORDERLINENUMBER IS NOT NULL),
ADD CHECK ( SALES IS NOT NULL),
ADD CHECK ( ORDERDATE  IS NOT NULL)


/*******3 Thêm cột CONTACTLASTNAME, CONTACTFIRSTNAME */

ALTER TABLE sales_dataset_rfm_prj
ADD COLUMN CONTACTLASTNAME VARCHAR(255),
ADD COLUMN CONTACTFIRSTNAME VARCHAR(255)

/*tạo bảng có chữa firt, last đã định dạng*/


CREATE TEMP TABLE AAA AS
(
SELECT 
UPPER (LEFT(CONTACTFULLNAME,1)) || 
	RIGHT(LEFT(CONTACTFULLNAME,POSITION('-' IN CONTACTFULLNAME)-1),
	  	LENGTH(LEFT(CONTACTFULLNAME,POSITION('-' IN CONTACTFULLNAME)-1))-1)
        AS CONTACTFIRSTNAME,
	
 UPPER (LEFT(right(CONTACTFULLNAME, LENGTH(CONTACTFULLNAME)-
			 LENGTH(LEFT(CONTACTFULLNAME,POSITION('-' IN CONTACTFULLNAME)))),1))
	|| right(right(CONTACTFULLNAME, LENGTH(CONTACTFULLNAME)-
			 LENGTH(LEFT(CONTACTFULLNAME,POSITION('-' IN CONTACTFULLNAME)))),
			 LENGTH(right(CONTACTFULLNAME, LENGTH(CONTACTFULLNAME)-
			 LENGTH(LEFT(CONTACTFULLNAME,POSITION('-' IN CONTACTFULLNAME)))-1)))
			 AS CONTACTLASTNAME
	
FROM sales_dataset_rfm_prj)

/* insert*/

INSERT INTO sales_dataset_rfm_prj(CONTACTFIRSTNAME,CONTACTLASTNAME)
SELECT CONTACTFIRSTNAME,CONTACTLASTNAME
FROM AAA;



SET datestyle = 'iso,mdy';  
ALTER TABLE sales_dataset_rfm_prj
ALTER COLUMN quantityordered TYPE numeric USING(trim(ordernumber)::numeric),
ALTER COLUMN priceeach TYPE decimal USING(trim(ordernumber)::decimal),
ALTER COLUMN orderlinenumber TYPE numeric USING(trim(ordernumber)::numeric),
ALTER COLUMN sales TYPE numeric USING(trim(ordernumber)::numeric),
ALTER COLUMN msrp TYPE numeric  USING(trim(ordernumber)::numeric),
ALTER COLUMN orderdate TYPE date USING(TRIM(orderdate)::time),
/*2. check null/blank*/ 
ALTER TABLE sales_dataset_rfm_prj
ADD CHECK ( ORDERNUMBER IS NOT NULL),
ADD CHECK ( QUANTITYORDERED IS NOT NULL),
ADD CHECK ( PRICEEACH IS NOT NULL),                      
ADD CHECK ( ORDERLINENUMBER IS NOT NULL),
ADD CHECK ( SALES IS NOT NULL),
ADD CHECK ( ORDERDATE  IS NOT NULL)

/*******3 Thêm cột CONTACTLASTNAME, CONTACTFIRSTNAME */

ALTER TABLE sales_dataset_rfm_prj
ADD COLUMN CONTACTLASTNAME VARCHAR(255),
ADD COLUMN CONTACTFIRSTNAME VARCHAR(255)

/*tạo bảng có chữa firt, last đã định dạng*/


CREATE TEMP TABLE AAA AS
(
SELECT 
UPPER (LEFT(CONTACTFULLNAME,1)) || 
	RIGHT(LEFT(CONTACTFULLNAME,POSITION('-' IN CONTACTFULLNAME)-1),
	  	LENGTH(LEFT(CONTACTFULLNAME,POSITION('-' IN CONTACTFULLNAME)-1))-1)
        AS CONTACTFIRSTNAME,
	
 UPPER (LEFT(right(CONTACTFULLNAME, LENGTH(CONTACTFULLNAME)-
			 LENGTH(LEFT(CONTACTFULLNAME,POSITION('-' IN CONTACTFULLNAME)))),1))
	|| right(right(CONTACTFULLNAME, LENGTH(CONTACTFULLNAME)-
			 LENGTH(LEFT(CONTACTFULLNAME,POSITION('-' IN CONTACTFULLNAME)))),
			 LENGTH(right(CONTACTFULLNAME, LENGTH(CONTACTFULLNAME)-
			 LENGTH(LEFT(CONTACTFULLNAME,POSITION('-' IN CONTACTFULLNAME)))-1)))
			 AS CONTACTLASTNAME
	
FROM sales_dataset_rfm_prj)

/* insert*/

INSERT INTO sales_dataset_rfm_prj(CONTACTFIRSTNAME,CONTACTLASTNAME)
SELECT CONTACTFIRSTNAME,CONTACTLASTNAME
FROM AAA;


	
	

